### ISSUE TITLE
got stuck at building vgg19 help please

### ISSUE THREAD

**Issue by silexxx** [VisiumCH/AMLD2020-Dirty-GANcing#3]
0 frames extracted
100 frames extracted
200 frames extracted
300 frames extracted
400 frames extracted
Bulding VGG19
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:207: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:209: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias, 0.0)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:212: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model1_1[8].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:213: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model1_2[8].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:215: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model2_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:216: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model3_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:217: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model4_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:218: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model5_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:219: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model6_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:221: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model2_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:222: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model3_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:223: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model4_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:224: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model5_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:225: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model6_2[12].weight, std=0.01)
Traceback (most recent call last):
  File "src/data_preparation/prepare_source.py", line 131, in <module>
    prepare_source(args.save_dir)
  File "src/data_preparation/prepare_source.py", line 40, in prepare_source
    model = load_openpose_model()
  File "src/data_preparation/prepare_source.py", line 62, in load_openpose_model
    model.load_state_dict(torch.load(weights))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Gramet** [comment]
Hi @silexxx 

This type of error might happen if `git-lfs` is not installed in your environment. Try running `git-lfs pull` once it is installed.

**Comment by silexxx** [comment]
yes thank you this worked i didnt knew git-lfs pull before I used to download manually and put now I got to know about this concept thank you
