### ISSUE TITLE
i ran into this error and i searched online i cant get enough support for this implimentation.

### ISSUE THREAD

**Issue by silexxx** [VisiumCH/AMLD2020-Dirty-GANcing#4]
0 frames extracted
100 frames extracted
200 frames extracted
300 frames extracted
400 frames extracted
Bulding VGG19
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:204: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:206: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias, 0.0)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:209: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model1_1[8].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:210: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model1_2[8].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:212: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model2_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:213: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model3_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:214: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model4_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:215: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model5_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:216: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model6_1[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:218: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model2_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:219: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model3_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:220: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model4_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:221: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model5_2[12].weight, std=0.01)
src/data_preparation/../PoseEstimation/network/rtpose_vgg.py:222: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.model6_2[12].weight, std=0.01)
 97% 448/464 [22:24<00:48,  3.00s/it]Traceback (most recent call last):
  File "src/data_preparation/prepare_source.py", line 131, in <module>
    prepare_source(args.save_dir)
  File "src/data_preparation/prepare_source.py", line 42, in prepare_source
    extract_poses(model, save_dir)
  File "src/data_preparation/prepare_source.py", line 86, in extract_poses
    shape_dst = np.min(img.shape[:2])
AttributeError: 'NoneType' object has no attribute 'shape'
 97% 448/464 [22:24<00:48,  3.00s/it]

**Comment by Gramet** [comment]
`img` is `None` because you tried to read an image file that doesn't seem to exist. 

The images are supposed to be created in the `extract_frames` function earlier. My guess is either your video is somehow corrupted, or you saved the images in a non-empty directory, which lead to the counter in `extract_poses` to mismatch and the loading of a non-existing file.

Let me know if that helps solving your issue. If that was the problem, I might add some code to avoid this problem.

**Comment by silexxx** [comment]
thank you for the reply actually I was running it through drive by connecting it to collab while I run it through drive it was not extracting those images to the driving drive was empty only when I run it in local machine its working perfect up to preparing then crashing at next stage I will open a new issue with it thank you for getting back.
