### ISSUE TITLE
MovieWriter imagemagick unavailable; trying to use pillow instead.

### ISSUE THREAD

**Issue by silexxx** [VisiumCH/AMLD2020-Dirty-GANcing#6]
when I run the last module command !python src/data_postprocessing/make_gif.py -s data/sources/source -r results/danesh
MovieWriter imagemagick unavailable; trying to use pillow instead.
Traceback (most recent call last):
  File "src/data_postprocessing/make_gif.py", line 72, in <module>
    make_gif(args.source_dir, args.results_dir)
  File "src/data_postprocessing/make_gif.py", line 60, in make_gif
    writer="imagemagick")
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/animation.py", line 1111, in save
    extra_args=extra_args, metadata=metadata)
TypeError: 'str' object is not callable

please help me I have almost at the end of it .

**Comment by silexxx** [comment]
I ran  make_video.py and got the result. but I am queries to know thats wrong in that  command thank you

**Comment by Gramet** [comment]
You are probably missing imagemagick writer on your computer.You can try to change l.60 of `make_gif.py` to another writer like mencoder or ffmpeg...

Did you get a satisfying result with make_video.py?

**Comment by Gramet** [comment]
You can also try this to see the available writers and choose the one you want.

```
import matplotlib.animation as manimation
manimation.writers.list()
```

**Comment by silexxx** [comment]
yes, it worked thank you for the response.
