### ISSUE TITLE
FileNotFoundError:[Error 2] No such file or directory: './checkpoints/test\\iter.json

### ISSUE THREAD

**Issue by justinjohn0306** [VisiumCH/AMLD2020-Dirty-GANcing#8]
![Capture](https://user-images.githubusercontent.com/34035011/94877930-93134680-0479-11eb-9e1a-257cf73f74f8.PNG)

Please send me this .json file or test me how to fix this

**Comment by Gramet** [comment]
Hello @justinjohn0306 ,

It looks like it's trying to load a pre-existing run, but can't find the `iter.json` file to resume the epochs. Either you deleted it by accident or there was a problem with an earlier run. I would suggest you delete the `checkpoints/test` directory so it doesn't attempt to resume a training that doesn't exist, this should solve the issue. Let me know if that fixes the issue

**Comment by justinjohn0306** [comment]
Returned with new error

**Comment by justinjohn0306** [comment]
> Hello @justinjohn0306 ,
> 
> It looks like it's trying to load a pre-existing run, but can't find the `iter.json` file to resume the epochs. Either you deleted it by accident or there was a problem with an earlier run. I would suggest you delete the `checkpoints/test` directory so it doesn't attempt to resume a training that doesn't exist, this should solve the issue. Let me know if that fixes the issue

![Capture](https://user-images.githubusercontent.com/34035011/94898430-2fa40b80-04af-11eb-8975-ba6d3fc5cbf4.PNG)

Returned with new error

**Comment by Gramet** [comment]
Did you delete the `test` directory or the whole `checkpoints` directory? I think you need the `checkpoints` directory to exist for this to work.

**Comment by Gramet** [comment]
Actually I just realized that you are on Windows, it might just be a path issue... Try to change the forward slashes of the variables defined in `config/train_opt.py` to backward slashes so the path work on Windows.

**Comment by justinjohn0306** [comment]
I kept checkpoints directory

**Comment by Gramet** [comment]
Hello @justinjohn0306 

Did you manage to get it to work with the Windows forward slashes?

**Comment by justinjohn0306** [comment]
> Hello @justinjohn0306
> 
> Did you manage to get it to work with the Windows forward slashes?

yup everything's A ok
